/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TradeSetupResult = IDL.Record({
  'explanation' : IDL.Text,
  'positionSize' : IDL.Float64,
  'riskRewardRatio' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InputData = IDL.Record({
  'riskAmount' : IDL.Float64,
  'takeProfitPrice' : IDL.Float64,
  'stopLossPrice' : IDL.Float64,
  'entryPrice' : IDL.Float64,
});
export const Time = IDL.Int;
export const TradeAnalysis = IDL.Record({
  'id' : IDL.Nat,
  'result' : TradeSetupResult,
  'inputData' : InputData,
  'ticker' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'analyzeTrade' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [TradeSetupResult],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTradeById' : IDL.Func([IDL.Nat], [TradeAnalysis], ['query']),
  'getTradeHistory' : IDL.Func([], [IDL.Vec(TradeAnalysis)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TradeSetupResult = IDL.Record({
    'explanation' : IDL.Text,
    'positionSize' : IDL.Float64,
    'riskRewardRatio' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InputData = IDL.Record({
    'riskAmount' : IDL.Float64,
    'takeProfitPrice' : IDL.Float64,
    'stopLossPrice' : IDL.Float64,
    'entryPrice' : IDL.Float64,
  });
  const Time = IDL.Int;
  const TradeAnalysis = IDL.Record({
    'id' : IDL.Nat,
    'result' : TradeSetupResult,
    'inputData' : InputData,
    'ticker' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'analyzeTrade' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [TradeSetupResult],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTradeById' : IDL.Func([IDL.Nat], [TradeAnalysis], ['query']),
    'getTradeHistory' : IDL.Func([], [IDL.Vec(TradeAnalysis)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };